require("settings")
require("custom_commands")
require("helper")
require("format_on_save")
require('mappings')
vim.cmd('source $HOME/.config/nvim/vim-plug/plugins.vim')
require("telescope_config")
require("treesitter")
require("completion")
require("lsp")
require('git_config')
require('colors')
require("bufferline_config")
require("lualine_config")
require("indent_blankline_config")
require("smooth_scroll")
require("comments")
